### ISSUE TITLE
Featue Request: Export define-tag-processor

### ISSUE THREAD

**Issue by cbaggers** [Shinmera/staple#2]
Being able to define a new processor is really nice when you want to add extra kinds of elements to ctml documents. In my case I wanted `do-symbols` to iterate on every external symbol, even if originally defined in another package.

I was able to do this but required using non external symbols (`define-tag-processor` `symbol-objects`)

Is this something that could be done, or have I overlooked some feature of Staple that already enable this?

**Comment by Shinmera** [comment]
`define-tag-processor` is external in the `clip` package.

You could achieve what you want by instead changing `package-symbols` to not perform the package test. I'm not sure what my original reasoning was for adding in that test to begin with, but I'll change that to instead allow removing them through an exclusion mask like the rest.

**Comment by Shinmera** [comment]
Ah, I remember now. In order to properly determine the "scope" of a symbol, you need to know both the symbol and the package. Staple's symbol handling throws away the package information once it has gathered all symbols from the package and then use's the symbol's home package instead, resulting in all inherited symbols always being external.

I'll see about fixing this.

**Comment by Shinmera** [comment]
Alright, should be fixed as of bfa7611e63f4503280ccb14258ce5baa44806984. The template has been updated to ignore inherited symbols as well b67bb763eb1857af4694a820a1e688f038d2f0b9, but note that this only means ignoring symbols that were inherited and not exported from that package. By default Staple now considers all exported symbols regardless of their origin package.
